In [2]:
import cvxpy as cp
import torch
from cvxpylayers.torch import CvxpyLayer

n, m = 2, 3
x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
constraints = [x >= 0]
objective = cp.Minimize(0.5 * cp.pnorm(A @ x - b, p=1))
problem = cp.Problem(objective, constraints)
assert problem.is_dpp()

cvxpylayer = CvxpyLayer(problem, parameters=[A, b], variables=[x])
A_tch = torch.randn(m, n, requires_grad=True)
b_tch = torch.randn(m, requires_grad=True)

# solve the problem
solution, = cvxpylayer(A_tch, b_tch)

# compute the gradient of the sum of the solution with respect to A, b
solution.sum().backward()

In [4]:
solution, A_tch.grad, b_tch.grad

(tensor([0.0983, 0.8106], grad_fn=<_CvxpyLayerFnFnBackward>),
 tensor([[1.6467e-01, 1.3574e+00],
         [4.5309e-07, 3.2892e-06],
         [1.4970e-03, 1.2340e-02]]),
 tensor([-1.6747e+00, -4.0636e-06, -1.5225e-02]))